#!/bin/sh

APP_PACKAGE="${0%/Contents/MacOS/*}"
JAVAROOT="$APP_PACKAGE/Contents/Resources/Java"

# SPaTo should have called System.exit by now, but give the VM some time to shut down
sleep 3

# Run the prelude
java -d32 -cp "$JAVAROOT" -Xdock:name="SPaTo Visual Explorer" -Xdock:icon="$APP_PACKAGE/Contents/Resources/spato.icns" -Dspato.logfile="$APP_PACKAGE/Contents/prelude.log" -Dspato.app-dir="$APP_PACKAGE" SPaTo_Prelude

# Launch SPaTo again
open "$APP_PACKAGE"