
WindowsMagic.class: WindowsMagic.java
	javac -source 1.5 -target 1.5 -cp WinRun4J.jar:../../application.windows/lib/SPaTo_Visual_Explorer.jar:../../application.windows/lib/core.jar WindowsMagic.java
